### ISSUE TITLE
Missing Authentication Token

### ISSUE THREAD

**Issue by agnelvishal** [PureStake/algosigner#113]
I would like to find the list of transactions of a address.
When I run the below code, I get "Missing Authentication Token" error message
```
await AlgoSigner.algod({
  ledger: 'MainNet',
  path: '/v2/accounts/GVZFXMO3QO5JMLQGQCYZG7SOWHZJ47BYUWXA6WDZOVJPFKX2M46X5C2YEU/transactions'
})
```
I am able to run the below code without any error
```
await AlgoSigner.algod({
  ledger: 'MainNet',
  path: '/v2/accounts/GVZFXMO3QO5JMLQGQCYZG7SOWHZJ47BYUWXA6WDZOVJPFKX2M46X5C2YEU'
})
```

**Comment by purestaketdb** [comment]
Greetings!

AlgoSigner uses the Algod v2 API which does NOT have that endpoint. In order to retrieve the account transactions you need to use the Indexer endpoint. 

Example:

```JSON
AlgoSigner.indexer({
   ledger: 'TestNet',
   path: '/v2/accounts/GVZFXMO3QO5JMLQGQCYZG7SOWHZJ47BYUWXA6WDZOVJPFKX2M46X5C2YEU/transactions',
});
```

**Comment by faiqnadeem** [comment]
hi i am having the same problem with Indexer  " new algosdk.Indexer(token, baseServer, port);"
Error: Network request error. Received status 403: Missing Authentication Token at Request.callback

please guide me through it...
