### ISSUE TITLE
Sign in screen blank sometimes.

### ISSUE THREAD

**Issue by agnelvishal** [PureStake/algosigner#114]
On an average of once every five times, the sign in page goes blank.
Below is the screenshot
![Screenshot from 2020-09-25 22-26-49](https://user-images.githubusercontent.com/10105332/94295446-de5fbd80-ff7e-11ea-97ac-fe0afc36ab7b.png)
Refreshing the page solves the problem.

Below is the error
```
main.js:1279 Uncaught (in promise) TypeError: Cannot read property 'length' of undefined
    at y.la [as constructor] (main.js:1279)
    at y.$ [as render] (main.js:1)
    at L (main.js:1)
    at main.js:1
    at Array.some (<anonymous>)
    at z (main.js:1)

```

**Comment by purestaketdb** [comment]
On deck for review - along with other possible issues related to connection

**Comment by PureBrent** [comment]
Unable to replicate and no other reported similar issues, closing.

**Comment by mataide** [comment]
It happens to me also

**Comment by janmarcano** [comment]
We'll take a second look at this
