### ISSUE TITLE
Newcomers become confused when creating account

### ISSUE THREAD

**Issue by agnelvishal** [PureStake/algosigner#115]
While creating account, I copy the Mnemonic and go to text editor to save the Mnemonic. When I return to the AlgoSigner extension, I am not shown the Mnemonic and address again. 
I can still import account with the Mnemonic and see the address. But newcomers become confused and paranoid that they were unable to copy the address at the first attempt. Newcomers would like to copy both the address and Mnemonic without going to the main screen. 

Attaching the related gif
![ezgif-1-60e33f269acd](https://user-images.githubusercontent.com/10105332/94302744-55e71a00-ff8a-11ea-92a6-a2565efac437.gif)

**Comment by purestaketdb** [comment]
At long last, we've added an in browser experience for creating the first account
