### ISSUE TITLE
Send a transaction from a re-keyed account

### ISSUE THREAD

**Issue by logiclogue** [PureStake/algosigner#120]
Hi,

I'm trying to sign a transaction from a re-keyed account. Here is the transaction I'm trying to sign where "GIADCL7O..." is the re-keyed account:

```
    window.AlgoSigner.sign({
        from: "GIADCL7OAX3IDFJKXI6ION5RJ55AQGAN33KAZQZNGCZOSKC2QQWP3UT7CU",
        to: context.meta.account,
        amount: 10000,
        note: "Footium:BLAH",
        type: "pay",
        fee: context.txParams['min-fee'],
        firstRound: context.txParams['last-round'],
        lastRound: context.txParams['last-round'] + 1000,
        genesisID: context.txParams['genesis-id'],
        genesisHash: context.txParams['genesis-hash']
    }).then(signedTx => {
        ...
```

However, it seems that I can't do this, as the error message is: `message: "from is not a valid user account."`

I have a feeling this isn't supported yet, or am I doing something wrong?

Many thanks,

**Comment by purestaketdb** [comment]
Rekeying is not currently supported in any scenario, for the mid-to-late November release we'll look at adding in support for the different ways it can play out.

**Comment by logiclogue** [comment]
Hi, is there any update on this? I'm wanting to sign a transaction from a different spending key

**Comment by purestaketdb** [comment]
Our current priorities are to support multi-signature signing and then dynamic/configurable networks. This is on the roadmap still but more than a month out.

**Comment by janmarcano** [comment]
it was a long time coming, but rekey support was added a few releases back :)

closing the issue
