### ISSUE TITLE
Question on signing a multisig with Algosigner

### ISSUE THREAD

**Issue by ddbit** [PureStake/algosigner#149]
Is it possible, given a multisig address **M** generated by addresses **A,B,C** and threshold = 2, to create a pay tx where 'from'=**M** and that I can sign with private key of **A** to generate the signed tx, and then hand over the signed tx to the other participant **B** to add his signature? I've found many examples on multisig but none with Algosigner as signer.

**Comment by purestaketdb** [comment]
The multi-sig feature is next on the roadmap. A release with Atomic (group) signing is releasing this week (by 11/20/2020) and in 2-3 weeks multi-sig will be ready.

**Comment by purestaketdb** [comment]
This is complete
