### ISSUE TITLE
Can't clear cached ASAs without deleting the wallet.

### ISSUE THREAD

**Issue by nullun** [PureStake/algosigner#206]
This scenario obviously shouldn't happen on mainnet, but when working in a sandbox network which is reset clearing all previous data, the ASAs shown within the accounts never clear/update and I don't seem to be able to force clear them without deleting the entire wallet and starting over. I have tried removing the individual accounts and importing them again, but that doesn't work either.

I've included a screenshot below, but it may look a little confusing. In summary, the two assets at the top labelled "First Asset #000x" were created via `goal asset create` and then viewed within AlgoSigner. I then reset the sandbox and created 4 new assets labelled "Second Asset #000x". However the first two have the same asset id of the previous two assets, so AlgoSigner doesn't seem to ever clear or update their name/unitname/decimal. I also show the JSON response of the current indexer, to show the real names of the first two assets.

![Screenshot from 2021-03-28 15-03-59](https://user-images.githubusercontent.com/974714/112755405-72671c00-8fd8-11eb-9c27-7af7a75d8699.png)

I suppose what I'm looking for is an enhancement to allow clearing the local asset cache without deleting the entire wallet.

**Comment by purestaketdb** [comment]
I've added this to our backlog -

**Comment by janmarcano** [comment]
A new option in the Settings menu will allow you to clear the local cache where Assets are pulled from.
It's currently available in the develop branch and should go out with the coming 1.7.0 release.

**Comment by janmarcano** [comment]
@nullun release 1.7.0 is out, can you confirm if this is still an issue?

**Comment by nullun** [comment]
> @nullun release 1.7.0 is out, can you confirm if this is still an issue?

So I thought I could test this quickly and give you the thumbs up, but as it turns out I was unable to add an asset whilst using my sandbox network.

![](https://i.imgur.com/ihchUjA.png)

I honestly haven't looked into this more than verifying my sandbox network was configured properly and I was pointing to the right URLs, is it possibly an old cached genesis id exists now? Apologies if the problem is on my end, I'll be able to play around some more later tonight or tomorrow.

**Comment by nullun** [comment]
Closing as I've attempted to replicate my issue without success. Working as expected now, thank you. :)
