### ISSUE TITLE
AlgoSigner UI got frozen

### ISSUE THREAD

**Issue by bitcoin333** [PureStake/algosigner#211]
After I installed it in Chrome, the UI got frozen several times. I was unable to go on. 
After I started Metamask, the UI began to work.

**Comment by purestaketdb** [comment]
That is somewhat unexpected. Do the accounts you have contain large number of assets? 

There is some setup and discovery, including asset names that happens on the first load, this might cause some issues. We are also looking at better handling for deleted assets which have other problems.

**Comment by PureBrent** [comment]
Not reproducible or experienced since.
