### ISSUE TITLE
Unable to connect to Sandbox

### ISSUE THREAD

**Issue by rdrobinson3** [PureStake/algosigner#214]
I have setup sandbox and am able to interact with the APIs using curl and the go-sdk. 

I have configured AlgoSigner's Sandbox network matching the configuration [in the 1.4 announcement blog post.](https://developer.algorand.org/articles/whats-new-in-algosigner-v14/) 

I imported my test account mnemonics into AlgoSigner with the proper network (Sandbox) selected. 

Once the accounts are imported and I select them the balances and the transactions never load. There is just a spinner below Transactions. 

My guess is there may be an issue with my headers? The README was cryptic and the blog post was the only reference I have found pointing me towards the expected header 

> Network Headers: Object stucture that will be used as replacement headers for calls. The object structure has an "Algod" and "Indexer" sub structure which will contain the headers the target api needs in order to function.

**Comment by purestaketdb** [comment]
Thank you for bringing this to our attention, we initially required the header construct and then switched to requiring it OR just the Algod token value. Neither expected value would be clear unless you've worked with the APIs and the JS SDK. I'll set up a webpage to document what should be done. 

In the meantime, the Algod API expects a key to be sent in with the request headers (X-Algo-API-Token), in the case of a Sandbox instance you can find the value by `./sandbox enter algod` and then `cat algod.token;`and placing the value into the Network Headers field. More about this token here (https://developer.algorand.org/docs/reference/sdks/#security-token)

For the PureStake APIs, for example to add BetaNet to AlgoSigner you need to use a full header object in the Network Headers field like `{"Algod":{"X-API-key":"<PS API KEY>"},"Indexer":{"X-API-Key":"<PS API KEY>"}}` The Key here is one you are assigned when registering at https://developer.purestake.io

![image](https://user-images.githubusercontent.com/45097828/114606788-bcebc800-9c69-11eb-9d5e-2eb5055b8e91.png)

**Comment by rdrobinson3** [comment]
Ahhh. Thanks for clearing that up. I was able to put just the token value in and successfully pull my transactions. I had tried all kinds of variations for the X-Algo-API-Token struct but never tried just putting in the key by itself. I appreciate the help.

**Comment by mkelly1495** [comment]
This does not work. I did the `cat algod.token` as suggested and it returned the `aaa...` long stream of a's key. I tried to to use this with the sandbox and it responded with a `401` "Invalid api key" message.

**Comment by mkelly1495** [comment]
Also the https://developer.algorand.org/docs/reference/sdks/#security-token page is invalid.

**Comment by janmarcano** [comment]
Hello @mkelly1495, here's the updated link to the Algorand documentation: https://developer.algorand.org/docs/rest-apis/restendpoints/#security-token

I recreated the key using `goal node generatetoken` and was able to connect to it successfully using AlgoSigner.
