### ISSUE TITLE
Firefox Release?

### ISSUE THREAD

**Issue by blabtonic** [PureStake/algosigner#215]
Is there any word on releasing this to firefox (or firefox forks) any time soon? Don't know if there are ways to upload this as developer version through the firefox add-on feature

**Comment by purestaketdb** [comment]
No update on development of this feature, it's still on the backlog but isn't a high priority at this time. 

You might be able to port to Firefox for your specific needs, we just can't commit at this time to porting the code base, verifying the security and all the features, and keeping it up to date with each feature release.
