### ISSUE TITLE
Failed to decode signed transaction blob

### ISSUE THREAD

**Issue by AChaffangeon** [PureStake/algosigner#217]
Using the function exposed in https://github.com/PureStake/algosigner-dapp-example/blob/master/python/pythonTransaction.py or a Uint8Array in javascript, we could not decode the blob of a signed transaction (for example the one from the group example in your dapp). Even other base64 decoders did not work. Is there a workaround to decode the blob without those functions? 

Thanks

**Comment by PureBrent** [comment]
Running the test app and get back a blob inside the signed transaction response:
{"txID":"IE4Q2TI4BI3CLMZ3NKIF6HRHZSGLTXAVUI2LT4BJ7WEEDULHBJXA","blob":"gqNzaWfEQJDkuh6YKyVnJoBF8YB8YLXa5BLq2Uet94xV3JTWsCXi9SYshuh6D510ZNqB9c/ojVhzdIAcQ3kwXF2fXKE1eQqjdHhuiaNhbXQFo2ZlZc0D6KJmds4A0ll9o2dlbqx0ZXN0bmV0LXYxLjCiZ2jEIEhjtRiks8hOyBDyLU8QgcsPcfBZp6wg3sYvf3DlCToiomx2zgDSXWWjcmN2xCB4cncpTQ0EIaQ/UHSlnoywjAYG+VGCUxgnw1tyoC7CPqNzbmTEINSXcyrLQaQxrF+OcfGwwruBZk/GAZ2wJZrU/Q5k2JtgpHR5cGWjcGF5"}

Using the blob as a string into the Python algosdk uses algosdk.encoding.msgpack_decode(), the response should be:
Signature: kOS6HpgrJWcmgEXxgHxgtdrkEurZR633jFXclNawJeL1JiyG6HoPnXRk2oH1z+iNWHN0gBxDeTBcXZ9coTV5Cg==
Transaction: {'sender': '2SLXGKWLIGSDDLC7RZY7DMGCXOAWMT6GAGO3AJM22T6Q4ZGYTNQHSOLSWA', 'fee': 1000, 'first_valid_round': 13785469, 
'last_valid_round': 13786469, 'note': None, 'genesis_id': 'testnet-v1.0', 'genesis_hash': 'SGO1GKSzyE7IEPItTxCByw9x8FmnrCDexi9/cOUJOiI=', 'group': None, 'lease': None, 'type': 'pay', 'rekey_to': None, 'receiver': 'PBZHOKKNBUCCDJB7KB2KLHUMWCGAMBXZKGBFGGBHYNNXFIBOYI7ONYBWK4', 'amt': 5, 'close_remainder_to': None}

That is for a normal pay transaction transaction with the Python code in the sdk using a base64 decode, then a mspack unpackb function. 
msgpack.unpackb(base64.b64decode(enc), raw=False)
