### ISSUE TITLE
Support the presence of the extraPages field

### ISSUE THREAD

**Issue by DanBurton** [PureStake/algosigner#267]
See: https://algorand.github.io/js-algorand-sdk/classes/transaction.html#extrapages

When I try to sign a transaction with this field using AlgoSigner (version 1.6.0 of the Chrome extension), I get:

```
"Creation of ApplTx has extra or invalid fields: extraPages."
```

**Comment by PureBrent** [comment]
The upgrade to using the js sdk 1.10.0 is slated for the 1.6.1 release which includes the extra-pages support. I'll add a ticket to explicitly verify it works for application transactions.

**Comment by janmarcano** [comment]
More info on this:

Issues appeared with 1.10.1, so we're updating to sdk-1.9.1 in the meantime for the AlgoSigner-1.6.1 release.
We'll focus on adding support for 1.10.1 on a different release.

**Comment by DanBurton** [comment]
I see there is a 1.6.1 release on github :tada:

When is this expected to land in the Chrome web store?

**Comment by purestaketdb** [comment]
The release is there now, but a user reported a further issue with extra pages that is under investigation

**Comment by DanBurton** [comment]
I can confirm that I am still experiencing the same issue with AlgoSigner 1.6.1 in Chrome.

**Comment by PureBrent** [comment]
The extraPages field is lost during an internal decodeUnsignedTransaction() to the sdk. An issue has been logged https://github.com/algorand/js-algorand-sdk/issues/418.
