### ISSUE TITLE
v2 Sign - converting circular structures error

### ISSUE THREAD

**Issue by purestaketdb** [PureStake/algosigner#280]
Reported by a user - will review internally and identify issue

1. Transaction a is an app creation call with args passed and has a signers: [] and signed separately by logisic, hence no need to sign by user via algosigner but i still provide it for group validation and to avoid (part of unknown transaction group warning)
2. Transaction b is a simple pay transaction that needs signing by user 

Here is what i experience when i use the v2 algosigner methods. 
If i encode the args array in app create transaction into a string - i get an error from algosigner that its a part of an unknown transaction group
If i don't encode it an leave as uint8array, i get the fancy new signer screen where i click sign for each transaction in a group, when i click sign for the last transaction in a group i get converting circular structures error. 

Hence, this blocks me from upgrading to v2 algosigner and i have to continue sending individual transactions for signing via v1 methods

**Comment by janmarcano** [comment]
Fixed by #272
