### ISSUE TITLE
Cannot connect to sandbox nodes

### ISSUE THREAD

**Issue by plasmatech8** [PureStake/algosigner#281]
I have been trying to connect to the private and test network (via sandbox) but I cannot get the extension to show balances for any accounts - instead balances go blank and the transactions don't show either.

Sometimes, the console for the extension throws `Error handling response: TypeError: Cannot read property 'length' of undefined at chrome-extension://kmmolakhbgdlpkjkcjkebenjheonagdm/main.js:1560:465`. Sometimes I think I had a CORs issue or something. 

Steps to reproduce:
```bash
git clone https://github.com/algorand/sandbox.git
cd sandbox
./sandbox up
```
Then:
* Network ID = sandnet-v1
* AlgoD URL = http://localhost:4001
* Indexer URL = http://localhost:8980
* Headers = aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa (+ tried other ways)

**Comment by janmarcano** [comment]
Should be fixed with #284, which should be included in the upcoming v1.6.2 release.
