### ISSUE TITLE
Wrong total displayed

### ISSUE THREAD

**Issue by AChaffangeon** [PureStake/algosigner#285]
Hello,

we noticed an error in the displayed total. 

For example, we are signing this algosdk transaction:
`p { amount: 6000000,
  fee: 1000
  flatFee: false
  from: {publicKey: Uint8Array(32), checksum: Uint8Array(4)}
  genesisHash: Uint8Array(32) 
  genesisID: "testnet-v1.0",
  group: undefined,
  lastRound: 16265985,
  name: "Transaction"
  note: Uint8Array(76) 
  tag: Uint8Array(2) 
  to: {publicKey: Uint8Array(32), checksum: Uint8Array(4)}
  type: "pay"
}`

However, while the raw transaction in AlgoSigner is correct, it displays an amount of 10006 Algos (see the pictures). Both amount and fee are passed as numbers to the transaction constructor.
<img width="411" alt="Screenshot 2021-08-26 at 20 44 11" src="https://user-images.githubusercontent.com/25482622/131019780-62f310e1-f12b-4643-ad91-67e689a52689.png">
<img width="397" alt="Screenshot 2021-08-26 at 20 44 31" src="https://user-images.githubusercontent.com/25482622/131019786-2ff12908-a411-4cd1-b51d-d269a4eadb15.png">

Any idea on how to fix this?

Thanks!

**Comment by janmarcano** [comment]
Hi! This is already fixed on #283 and should be available on the v1.6.2 release.

The wrong total is only a **display** issue on `Payment txs` and is not affecting the underlying transaction (as you can see it's correct on the `Details` tab), so feel free to keep using it as-is in the meantime.
