### ISSUE TITLE
Firefox extension

### ISSUE THREAD

**Issue by DevJackSmith** [PureStake/algosigner#324]
Algosigner chrome extension loads on Firefox as it is. I don't know if all the features work, but we can report here if any don't work. Since it's the same code base, can we get someone to test and submit it to Mozilla add-on store? 

(I know previous ticket said there's only 3% Firefox users, but we have to keep in mind that it's because of corporations using chrome for everything. On personal computers i'm sure Firefox usage is much higher. Not to mention this takes very little effort)

For those who want to use Algosigner in Firefox right now, it is not supported (yet), hopefully this ticket addresses it. But it is possible if you load it through Menu -> Addons ... -> ⚙️ -> Debug Add-ons -> Load Temporary Addon -> Select manifest file from dist folder. Again, ⚠️ **This is not officially supported, and if you lose everything doing this, no one is responsible but you**. ⚠️

**Comment by DevJackSmith** [comment]
So first difference in FF is that once I click on the extension icon -> Get Started -> Enter password twice -> Create Wallet, i get an error: `right-hand side of 'in' should be an object, got undefined`
I believe it is referencing `if ('error' in response) {` on line 44 of packages/ui/src/pages/SetPassword.ts

The response is coming from SendMessage function callback, in packages/ui/src/services/Messaging.ts which uses chrome.runtime.SendMessage().

That function chrome.runtime.SendMessage() is different in Firefox. But the version used by Firefox is supported by Chrome too, so we can fix this I believe.
Here are the details on FF version, which uses promise, and at the bottom we can find link to chrome version, which uses callback. https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/sendMessage

Replacing callback with promise.then(callback) like shown in the doc above should work. (Haven't been able to fix it on my local yet, but I believe it's a start)

**Comment by blabtonic** [comment]
much thanks
