### ISSUE TITLE
Unable to sign transaction w/ 2nd Ledger Nano S account

### ISSUE THREAD

**Issue by cccassidy** [PureStake/algosigner#350]
I have a Nano S with multiple Algo accounts.  While I was able to add the 2nd account to AlgoSigner and opt into Tinyman and Yieldly, I am unable to run any swaps on Tinyman.  The extension prompts to sign the transactions for the swap but it never sends the transaction to the Ledger and the site returns an error: 

`There was a problem signing the transaction(s).`

The same error throws if I run it without the Ledger attached so it seems to act like it can't find the device (even though I am able to connect the wallet to the website and it sees both accounts)

1/28 Update:
As a followup I am now unable to sign any transactions with the Ledger Nano S, even a simple send between accounts. After clicking "Send Transaction To Device" it just sits and spins. I can remove/re-add the accounts to the extension so it is at least able to communicate with the Ledger and find accounts, but for some reason never sends over transactions for signing.

Environment details:
OS: Windows 10 (also the same issue with Ubuntu 20.04)
Ledger Firmware 2.1.0
Ledger Algo App 1.2.15

**Comment by cccassidy** [comment]
As a followup I am now unable to sign any transactions with the Ledger Nano S, even a simple send between accounts.  After clicking "Send Transaction To Device" it just sits and spins.  I can remove/re-add the accounts to the extension so it is at least able to communicate with the Ledger and find accounts, but for some reason never sends over transactions for signing.

**Comment by janmarcano** [comment]
Hi! Thanks for the report, I'll be taking a look into this and get back to you if I find anything.

**Comment by janmarcano** [comment]
Hi @cccassidy

Regarding the Tinyman swaps: currently we don't support signing more than 1 Ledger transaction in a single group at once using AlgoSigner. By looking the Tinyman swaps, 2 of the group transactions require a signature from the Ledger device: the first I'm guessing is getting Algos to pay for the fees, and the second one is the actual ASA to swap. So unless they implement fee pooling to avoid creating an extra transaction, it's not going to work on Ledger devices using AlgoSigner for now.

In regards to your `1/28 Update`: we've identified an issue with Ledger signing from the UI. We have a fix ready that should come with a next release in the coming weeks.

**Comment by cccassidy** [comment]
Hi @janmarcano Appreciate the info, and will be on the lookout for the update to fix the 1/28 Ledger signing issue!

**Comment by janmarcano** [comment]
@cccassidy Version 1.7.3 should be live in the store with the fix for using Ledger devices on UI-made transactions. 
Closing this as the Tinyman issue is currently out of our hands, I've already reached out to them.
Let us know if you find any further issues, cheers.
