### ISSUE TITLE
How to call the `AlgoSigner` class with typscript ?

### ISSUE THREAD

**Issue by darmawan01** [PureStake/algosigner#394]
Hi,

How to call the `AlgoSigner` class with typscript. i am getting error 
```
Cannot find name 'AlgoSigner'.
```

**Comment by janmarcano** [comment]
Hi! 

The AlgoSigner object is available via the installed extension and exists on the `window` object in a browser.
You could either declare it as a global variable (always making sure to only call it when in a browser context) or reference it by doing 'window.AlgoSigner'
