### ISSUE TITLE
Pressing ctrl+shift+T reopens the algosigner window

### ISSUE THREAD

**Issue by kashishkhullar** [PureStake/algosigner#397]
If you press ctrl+shift+T on chrome after using the algosigner wallet, it should open the last closed Tab. This instead opens the algosigner wallet extension window, though blank.

**Comment by janmarcano** [comment]
I was not able to reproduce this, which browser are you using?
Also, could you please tell me if you were using a Ledger account by any chance.

**Comment by kashishkhullar** [comment]
**Steps to replicate:**

1. Go to [algosigner-dapp-example](https://purestake.github.io/algosigner-dapp-example/asset-create.html)
2. Go to the Tab **Asset Create Txn**
3. Perform all the step before Sign
4. Click on Sign and close the algosigner prompt
5. Press Ctrl + Shift + T to see the dialog box reappearing but blank.

**Comment by purestaketdb** [comment]
This out of our control as a browser function, in addition team couldn't reproduce
