### ISSUE TITLE
No Pop Up to Submit vote for Governance

### ISSUE THREAD

**Issue by jechev4** [PureStake/algosigner#409]
Voting in period #3 voting session 1 - Clicking submit vote produces [RequestError.NotAuthorized] instead of a popup asking to submit votes in Algosigner. The account is signed in, has the transaction ID (with 0 algo commited) and is cleared for governance in current voting session.

Produces the following error:
<img width="362" alt="requesterror" src="https://user-images.githubusercontent.com/81246149/171967073-30830563-ea47-43a8-93e2-0c462c78dfc9.png">

**Comment by jechev4** [comment]
Thank you, this seemed to fix the issue! I had tried logging out exclusively to no avail but it seems disconnecting and reconnecting the wallet on the Algorand Governance site with logging out did the trick.

**Comment by janmarcano** [comment]
Glad we were able to help!
