### ISSUE TITLE
Inclusion of empty "signers" array in groups returns error "address appears to be malformed"

### ISSUE THREAD

**Issue by headline-design** [PureStake/algosigner#437]
When working with group transactions that include logicsigs,  both attempting to add empty "signer" arrays (as per documentation), and filling the signer array with the address results in the following error: 

> _"Validation failed for transaction [index] due to: address seems to be malformed."_

**Comment by janmarcano** [comment]
Do you get the same error when using empty `signers`?

If you don't mind, could you share a code snippet of the transaction object with empty signers you're calling AlgoSigner with? Filling the array only works for multisig transactions, for logicsic the empty array would be the correct procedure.

**Comment by headline-design** [comment]
"Filling the array only works for multi-sig transactions, for logicsig the empty array would be the correct procedure."
- Yes, we've implemented that method and received the same error as noted above.

Here is an example transaction: [
    [
        {
            "txn": "iqRhcGFhkcQDYnV5pGFwaWTOMFoE7qNmZWXNA+iiZnbOAWGSVKNnZW6sbWFpbm5ldC12MS4womdoxCDAYcTY/B293tLXYEvkVo4/bQQZh6w3veS2ILWrOSSK36NncnDEIB4PNlbyvGtrt8Uq6uZ8aqYMcMHJmngBhtpBsve8Cc/romx2zgFhljyjc25kxCBc4F8LXjyJch+T5cUiULDZqIdVBULVKu6CfEIVdU5jtqR0eXBlpGFwcGw="
        },
        {
            "txn": "iqNhbXTODuaygKNmZWXNA+iiZnbOAWGSVKNnZW6sbWFpbm5ldC12MS4womdoxCDAYcTY/B293tLXYEvkVo4/bQQZh6w3veS2ILWrOSSK36NncnDEIB4PNlbyvGtrt8Uq6uZ8aqYMcMHJmngBhtpBsve8Cc/romx2zgFhljyjcmN2xCAsIwqlhsYZ+tMxWviFXaem4C4X41XMBznwnICekYnR7qNzbmTEIFzgXwtePIlyH5PlxSJQsNmoh1UFQtUq7oJ8QhV1TmO2pHR5cGWjcGF5"
        },
        {
            "txn": "jKRhYW10AaZhY2xvc2XEICwjCqWGxhn60zFa+IVdp6bgLhfjVcwHOfCcgJ6RidHupGFyY3bEIFzgXwtePIlyH5PlxSJQsNmoh1UFQtUq7oJ8QhV1TmO2o2ZlZc0D6KJmds4BYZJUo2dlbqxtYWlubmV0LXYxLjCiZ2jEIMBhxNj8Hb3e0tdgS+RWjj9tBBmHrDe95LYgtas5JIrfo2dycMQgHg82VvK8a2u3xSrq5nxqpgxwwcmaeAGG2kGy97wJz+uibHbOAWGWPKNzbmTEIJVoS8hEaQWTqmTOsy/RFI8YBKDrwbG59hvtY+RUkyVcpHR5cGWlYXhmZXKkeGFpZM4wWgRP",
            "signers": []
        },
        {
            "txn": "iqNhbXTOAHOYz6NmZWXNA+iiZnbOAWGSVKNnZW6sbWFpbm5ldC12MS4womdoxCDAYcTY/B293tLXYEvkVo4/bQQZh6w3veS2ILWrOSSK36NncnDEIB4PNlbyvGtrt8Uq6uZ8aqYMcMHJmngBhtpBsve8Cc/romx2zgFhljyjcmN2xCB6p2xlLPPNeHFnmGjsqAbo0VRaAgYAk0m+Pgv5nsvgX6NzbmTEIFzgXwtePIlyH5PlxSJQsNmoh1UFQtUq7oJ8QhV1TmO2pHR5cGWjcGF5"
        },
        {
            "txn": "iaVjbG9zZcQgLCMKpYbGGfrTMVr4hV2npuAuF+NVzAc58JyAnpGJ0e6jZmVlzQPoomZ2zgFhklSjZ2VurG1haW5uZXQtdjEuMKJnaMQgwGHE2Pwdvd7S12BL5FaOP20EGYesN73ktiC1qzkkit+jZ3JwxCAeDzZW8rxra7fFKurmfGqmDHDByZp4AYbaQbL3vAnP66Jsds4BYZY8o3NuZMQglWhLyERpBZOqZM6zL9EUjxgEoOvBsbn2G+1j5FSTJVykdHlwZaNwYXk=",
            "signers": []
        }
    ]
]

**Comment by headline-design** [comment]
-------------------
Unencoded
-------------------

[
    {
        "name": "Transaction",
        "tag": {
            "type": "Buffer",
            "data": [
                84,
                88
            ]
        },
        "type": "appl",
        "from": {
            "publicKey": {
                "0": 92,
                "1": 224,
                "2": 95,
                "3": 11,
                "4": 94,
                "5": 60,
                "6": 137,
                "7": 114,
                "8": 31,
                "9": 147,
                "10": 229,
                "11": 197,
                "12": 34,
                "13": 80,
                "14": 176,
                "15": 217,
                "16": 168,
                "17": 135,
                "18": 85,
                "19": 5,
                "20": 66,
                "21": 213,
                "22": 42,
                "23": 238,
                "24": 130,
                "25": 124,
                "26": 66,
                "27": 21,
                "28": 117,
                "29": 78,
                "30": 99,
                "31": 182
            },
            "checksum": {
                "0": 144,
                "1": 160,
                "2": 187,
                "3": 13
            }
        },
        "appIndex": 866790563,
        "appOnComplete": 0,
        "appArgs": [
            {
                "0": 98,
                "1": 117,
                "2": 121
            }
        ],
        "appForeignAssets": [
            866770282
        ],
        "note": {},
        "lease": {},
        "flatFee": false,
        "genesisHash": {
            "type": "Buffer",
            "data": [
                192,
                97,
                196,
                216,
                252,
                29,
                189,
                222,
                210,
                215,
                96,
                75,
                228,
                86,
                142,
                63,
                109,
                4,
                25,
                135,
                172,
                55,
                189,
                228,
                182,
                32,
                181,
                171,
                57,
                36,
                138,
                223
            ]
        },
        "fee": 1000,
        "firstRound": 23474161,
        "lastRound": 23475161,
        "genesisID": "mainnet-v1.0",
        "group": {
            "type": "Buffer",
            "data": [
                150,
                68,
                115,
                163,
                178,
                37,
                72,
                42,
                187,
                79,
                232,
                188,
                12,
                37,
                90,
                247,
                233,
                50,
                126,
                249,
                21,
                244,
                13,
                82,
                158,
                95,
                103,
                38,
                171,
                229,
                49,
                73
            ]
        }
    },
    {
        "name": "Transaction",
        "tag": {
            "type": "Buffer",
            "data": [
                84,
                88
            ]
        },
        "from": {
            "publicKey": {
                "0": 92,
                "1": 224,
                "2": 95,
                "3": 11,
                "4": 94,
                "5": 60,
                "6": 137,
                "7": 114,
                "8": 31,
                "9": 147,
                "10": 229,
                "11": 197,
                "12": 34,
                "13": 80,
                "14": 176,
                "15": 217,
                "16": 168,
                "17": 135,
                "18": 85,
                "19": 5,
                "20": 66,
                "21": 213,
                "22": 42,
                "23": 238,
                "24": 130,
                "25": 124,
                "26": 66,
                "27": 21,
                "28": 117,
                "29": 78,
                "30": 99,
                "31": 182
            },
            "checksum": {
                "0": 144,
                "1": 160,
                "2": 187,
                "3": 13
            }
        },
        "to": {
            "publicKey": {
                "0": 239,
                "1": 102,
                "2": 234,
                "3": 102,
                "4": 76,
                "5": 240,
                "6": 28,
                "7": 175,
                "8": 188,
                "9": 84,
                "10": 159,
                "11": 221,
                "12": 217,
                "13": 91,
                "14": 18,
                "15": 109,
                "16": 6,
                "17": 51,
                "18": 77,
                "19": 196,
                "20": 52,
                "21": 32,
                "22": 21,
                "23": 101,
                "24": 247,
                "25": 222,
                "26": 145,
                "27": 232,
                "28": 188,
                "29": 0,
                "30": 183,
                "31": 21
            },
            "checksum": {
                "0": 73,
                "1": 35,
                "2": 190,
                "3": 23
            }
        },
        "amount": 10000000,
        "note": {},
        "type": "pay",
        "flatFee": false,
        "genesisHash": {
            "type": "Buffer",
            "data": [
                192,
                97,
                196,
                216,
                252,
                29,
                189,
                222,
                210,
                215,
                96,
                75,
                228,
                86,
                142,
                63,
                109,
                4,
                25,
                135,
                172,
                55,
                189,
                228,
                182,
                32,
                181,
                171,
                57,
                36,
                138,
                223
            ]
        },
        "fee": 1000,
        "firstRound": 23474161,
        "lastRound": 23475161,
        "genesisID": "mainnet-v1.0",
        "appArgs": [],
        "lease": {},
        "group": {
            "type": "Buffer",
            "data": [
                150,
                68,
                115,
                163,
                178,
                37,
                72,
                42,
                187,
                79,
                232,
                188,
                12,
                37,
                90,
                247,
                233,
                50,
                126,
                249,
                21,
                244,
                13,
                82,
                158,
                95,
                103,
                38,
                171,
                229,
                49,
                73
            ]
        }
    },
    {
        "name": "Transaction",
        "tag": {
            "type": "Buffer",
            "data": [
                84,
                88
            ]
        },
        "type": "axfer",
        "from": {
            "publicKey": {
                "0": 4,
                "1": 40,
                "2": 207,
                "3": 138,
                "4": 40,
                "5": 185,
                "6": 161,
                "7": 152,
                "8": 132,
                "9": 11,
                "10": 136,
                "11": 117,
                "12": 66,
                "13": 99,
                "14": 233,
                "15": 225,
                "16": 182,
                "17": 85,
                "18": 209,
                "19": 196,
                "20": 51,
                "21": 178,
                "22": 20,
                "23": 210,
                "24": 238,
                "25": 77,
                "26": 230,
                "27": 253,
                "28": 136,
                "29": 110,
                "30": 206,
                "31": 197
            },
            "checksum": {
                "0": 57,
                "1": 17,
                "2": 25,
                "3": 228
            }
        },
        "to": {
            "publicKey": {
                "0": 92,
                "1": 224,
                "2": 95,
                "3": 11,
                "4": 94,
                "5": 60,
                "6": 137,
                "7": 114,
                "8": 31,
                "9": 147,
                "10": 229,
                "11": 197,
                "12": 34,
                "13": 80,
                "14": 176,
                "15": 217,
                "16": 168,
                "17": 135,
                "18": 85,
                "19": 5,
                "20": 66,
                "21": 213,
                "22": 42,
                "23": 238,
                "24": 130,
                "25": 124,
                "26": 66,
                "27": 21,
                "28": 117,
                "29": 78,
                "30": 99,
                "31": 182
            },
            "checksum": {
                "0": 144,
                "1": 160,
                "2": 187,
                "3": 13
            }
        },
        "amount": 1,
        "assetIndex": 866770282,
        "note": {},
        "closeRemainderTo": {
            "publicKey": {
                "0": 239,
                "1": 102,
                "2": 234,
                "3": 102,
                "4": 76,
                "5": 240,
                "6": 28,
                "7": 175,
                "8": 188,
                "9": 84,
                "10": 159,
                "11": 221,
                "12": 217,
                "13": 91,
                "14": 18,
                "15": 109,
                "16": 6,
                "17": 51,
                "18": 77,
                "19": 196,
                "20": 52,
                "21": 32,
                "22": 21,
                "23": 101,
                "24": 247,
                "25": 222,
                "26": 145,
                "27": 232,
                "28": 188,
                "29": 0,
                "30": 183,
                "31": 21
            },
            "checksum": {
                "0": 73,
                "1": 35,
                "2": 190,
                "3": 23
            }
        },
        "flatFee": true,
        "genesisHash": {
            "type": "Buffer",
            "data": [
                192,
                97,
                196,
                216,
                252,
                29,
                189,
                222,
                210,
                215,
                96,
                75,
                228,
                86,
                142,
                63,
                109,
                4,
                25,
                135,
                172,
                55,
                189,
                228,
                182,
                32,
                181,
                171,
                57,
                36,
                138,
                223
            ]
        },
        "fee": 1000,
        "firstRound": 23474161,
        "lastRound": 23475161,
        "genesisID": "mainnet-v1.0",
        "appArgs": [],
        "lease": {},
        "group": {
            "type": "Buffer",
            "data": [
                150,
                68,
                115,
                163,
                178,
                37,
                72,
                42,
                187,
                79,
                232,
                188,
                12,
                37,
                90,
                247,
                233,
                50,
                126,
                249,
                21,
                244,
                13,
                82,
                158,
                95,
                103,
                38,
                171,
                229,
                49,
                73
            ]
        }
    },
    {
        "name": "Transaction",
        "tag": {
            "type": "Buffer",
            "data": [
                84,
                88
            ]
        },
        "from": {
            "publicKey": {
                "0": 92,
                "1": 224,
                "2": 95,
                "3": 11,
                "4": 94,
                "5": 60,
                "6": 137,
                "7": 114,
                "8": 31,
                "9": 147,
                "10": 229,
                "11": 197,
                "12": 34,
                "13": 80,
                "14": 176,
                "15": 217,
                "16": 168,
                "17": 135,
                "18": 85,
                "19": 5,
                "20": 66,
                "21": 213,
                "22": 42,
                "23": 238,
                "24": 130,
                "25": 124,
                "26": 66,
                "27": 21,
                "28": 117,
                "29": 78,
                "30": 99,
                "31": 182
            },
            "checksum": {
                "0": 144,
                "1": 160,
                "2": 187,
                "3": 13
            }
        },
        "to": {
            "publicKey": {
                "0": 122,
                "1": 167,
                "2": 108,
                "3": 101,
                "4": 44,
                "5": 243,
                "6": 205,
                "7": 120,
                "8": 113,
                "9": 103,
                "10": 152,
                "11": 104,
                "12": 236,
                "13": 168,
                "14": 6,
                "15": 232,
                "16": 209,
                "17": 84,
                "18": 90,
                "19": 2,
                "20": 6,
                "21": 0,
                "22": 147,
                "23": 73,
                "24": 190,
                "25": 62,
                "26": 11,
                "27": 249,
                "28": 158,
                "29": 203,
                "30": 224,
                "31": 95
            },
            "checksum": {
                "0": 80,
                "1": 183,
                "2": 105,
                "3": 234
            }
        },
        "amount": 1000000,
        "note": {},
        "type": "pay",
        "flatFee": false,
        "genesisHash": {
            "type": "Buffer",
            "data": [
                192,
                97,
                196,
                216,
                252,
                29,
                189,
                222,
                210,
                215,
                96,
                75,
                228,
                86,
                142,
                63,
                109,
                4,
                25,
                135,
                172,
                55,
                189,
                228,
                182,
                32,
                181,
                171,
                57,
                36,
                138,
                223
            ]
        },
        "fee": 1000,
        "firstRound": 23474161,
        "lastRound": 23475161,
        "genesisID": "mainnet-v1.0",
        "appArgs": [],
        "lease": {},
        "group": {
            "type": "Buffer",
            "data": [
                150,
                68,
                115,
                163,
                178,
                37,
                72,
                42,
                187,
                79,
                232,
                188,
                12,
                37,
                90,
                247,
                233,
                50,
                126,
                249,
                21,
                244,
                13,
                82,
                158,
                95,
                103,
                38,
                171,
                229,
                49,
                73
            ]
        }
    },
    {
        "name": "Transaction",
        "tag": {
            "type": "Buffer",
            "data": [
                84,
                88
            ]
        },
        "from": {
            "publicKey": {
                "0": 4,
                "1": 40,
                "2": 207,
                "3": 138,
                "4": 40,
                "5": 185,
                "6": 161,
                "7": 152,
                "8": 132,
                "9": 11,
                "10": 136,
                "11": 117,
                "12": 66,
                "13": 99,
                "14": 233,
                "15": 225,
                "16": 182,
                "17": 85,
                "18": 209,
                "19": 196,
                "20": 51,
                "21": 178,
                "22": 20,
                "23": 210,
                "24": 238,
                "25": 77,
                "26": 230,
                "27": 253,
                "28": 136,
                "29": 110,
                "30": 206,
                "31": 197
            },
            "checksum": {
                "0": 57,
                "1": 17,
                "2": 25,
                "3": 228
            }
        },
        "amount": 0,
        "closeRemainderTo": {
            "publicKey": {
                "0": 239,
                "1": 102,
                "2": 234,
                "3": 102,
                "4": 76,
                "5": 240,
                "6": 28,
                "7": 175,
                "8": 188,
                "9": 84,
                "10": 159,
                "11": 221,
                "12": 217,
                "13": 91,
                "14": 18,
                "15": 109,
                "16": 6,
                "17": 51,
                "18": 77,
                "19": 196,
                "20": 52,
                "21": 32,
                "22": 21,
                "23": 101,
                "24": 247,
                "25": 222,
                "26": 145,
                "27": 232,
                "28": 188,
                "29": 0,
                "30": 183,
                "31": 21
            },
            "checksum": {
                "0": 73,
                "1": 35,
                "2": 190,
                "3": 23
            }
        },
        "note": {},
        "type": "pay",
        "flatFee": true,
        "genesisHash": {
            "type": "Buffer",
            "data": [
                192,
                97,
                196,
                216,
                252,
                29,
                189,
                222,
                210,
                215,
                96,
                75,
                228,
                86,
                142,
                63,
                109,
                4,
                25,
                135,
                172,
                55,
                189,
                228,
                182,
                32,
                181,
                171,
                57,
                36,
                138,
                223
            ]
        },
        "fee": 1000,
        "firstRound": 23474161,
        "lastRound": 23475161,
        "genesisID": "mainnet-v1.0",
        "appArgs": [],
        "lease": {},
        "group": {
            "type": "Buffer",
            "data": [
                150,
                68,
                115,
                163,
                178,
                37,
                72,
                42,
                187,
                79,
                232,
                188,
                12,
                37,
                90,
                247,
                233,
                50,
                126,
                249,
                21,
                244,
                13,
                82,
                158,
                95,
                103,
                38,
                171,
                229,
                49,
                73
            ]
        }
    },
    {
        "name": "Transaction",
        "tag": {
            "type": "Buffer",
            "data": [
                84,
                88
            ]
        },
        "from": {
            "publicKey": {
                "0": 92,
                "1": 224,
                "2": 95,
                "3": 11,
                "4": 94,
                "5": 60,
                "6": 137,
                "7": 114,
                "8": 31,
                "9": 147,
                "10": 229,
                "11": 197,
                "12": 34,
                "13": 80,
                "14": 176,
                "15": 217,
                "16": 168,
                "17": 135,
                "18": 85,
                "19": 5,
                "20": 66,
                "21": 213,
                "22": 42,
                "23": 238,
                "24": 130,
                "25": 124,
                "26": 66,
                "27": 21,
                "28": 117,
                "29": 78,
                "30": 99,
                "31": 182
            },
            "checksum": {
                "0": 144,
                "1": 160,
                "2": 187,
                "3": 13
            }
        },
        "to": {
            "publicKey": {
                "0": 239,
                "1": 102,
                "2": 234,
                "3": 102,
                "4": 76,
                "5": 240,
                "6": 28,
                "7": 175,
                "8": 188,
                "9": 84,
                "10": 159,
                "11": 221,
                "12": 217,
                "13": 91,
                "14": 18,
                "15": 109,
                "16": 6,
                "17": 51,
                "18": 77,
                "19": 196,
                "20": 52,
                "21": 32,
                "22": 21,
                "23": 101,
                "24": 247,
                "25": 222,
                "26": 145,
                "27": 232,
                "28": 188,
                "29": 0,
                "30": 183,
                "31": 21
            },
            "checksum": {
                "0": 73,
                "1": 35,
                "2": 190,
                "3": 23
            }
        },
        "amount": 1000000,
        "note": {},
        "type": "pay",
        "flatFee": false,
        "genesisHash": {
            "type": "Buffer",
            "data": [
                192,
                97,
                196,
                216,
                252,
                29,
                189,
                222,
                210,
                215,
                96,
                75,
                228,
                86,
                142,
                63,
                109,
                4,
                25,
                135,
                172,
                55,
                189,
                228,
                182,
                32,
                181,
                171,
                57,
                36,
                138,
                223
            ]
        },
        "fee": 1000,
        "firstRound": 23474161,
        "lastRound": 23475161,
        "genesisID": "mainnet-v1.0",
        "appArgs": [],
        "lease": {},
        "group": {
            "type": "Buffer",
            "data": [
                150,
                68,
                115,
                163,
                178,
                37,
                72,
                42,
                187,
                79,
                232,
                188,
                12,
                37,
                90,
                247,
                233,
                50,
                126,
                249,
                21,
                244,
                13,
                82,
                158,
                95,
                103,
                38,
                171,
                229,
                49,
                73
            ]
        }
    }
]

-------------------
Encoded
-------------------

[
    [
        {
            "txn": "i6RhcGFhkcQDYnV5pGFwYXORzjOp3WqkYXBpZM4zqiyjo2ZlZc0D6KJmds4BZi/xo2dlbqxtYWlubmV0LXYxLjCiZ2jEIMBhxNj8Hb3e0tdgS+RWjj9tBBmHrDe95LYgtas5JIrfo2dycMQglkRzo7IlSCq7T+i8DCVa9+kyfvkV9A1Snl9nJqvlMUmibHbOAWYz2aNzbmTEIFzgXwtePIlyH5PlxSJQsNmoh1UFQtUq7oJ8QhV1TmO2pHR5cGWkYXBwbA=="
        },
        {
            "txn": "iqNhbXTOAJiWgKNmZWXNA+iiZnbOAWYv8aNnZW6sbWFpbm5ldC12MS4womdoxCDAYcTY/B293tLXYEvkVo4/bQQZh6w3veS2ILWrOSSK36NncnDEIJZEc6OyJUgqu0/ovAwlWvfpMn75FfQNUp5fZyar5TFJomx2zgFmM9mjcmN2xCDvZupmTPAcr7xUn93ZWxJtBjNNxDQgFWX33pHovAC3FaNzbmTEIFzgXwtePIlyH5PlxSJQsNmoh1UFQtUq7oJ8QhV1TmO2pHR5cGWjcGF5"
        },
        {
            "txn": "jKRhYW10AaZhY2xvc2XEIO9m6mZM8ByvvFSf3dlbEm0GM03ENCAVZffekei8ALcVpGFyY3bEIFzgXwtePIlyH5PlxSJQsNmoh1UFQtUq7oJ8QhV1TmO2o2ZlZc0D6KJmds4BZi/xo2dlbqxtYWlubmV0LXYxLjCiZ2jEIMBhxNj8Hb3e0tdgS+RWjj9tBBmHrDe95LYgtas5JIrfo2dycMQglkRzo7IlSCq7T+i8DCVa9+kyfvkV9A1Snl9nJqvlMUmibHbOAWYz2aNzbmTEIAQoz4oouaGYhAuIdUJj6eG2VdHEM7IU0u5N5v2Ibs7FpHR5cGWlYXhmZXKkeGFpZM4zqd1q",
            "signers": [
                "AQUM7CRIXGQZRBALRB2UEY7J4G3FLUOEGOZBJUXOJXTP3CDOZ3CTSEIZ4Q"
            ]
        },
        {
            "txn": "iqNhbXTOAA9CQKNmZWXNA+iiZnbOAWYv8aNnZW6sbWFpbm5ldC12MS4womdoxCDAYcTY/B293tLXYEvkVo4/bQQZh6w3veS2ILWrOSSK36NncnDEIJZEc6OyJUgqu0/ovAwlWvfpMn75FfQNUp5fZyar5TFJomx2zgFmM9mjcmN2xCB6p2xlLPPNeHFnmGjsqAbo0VRaAgYAk0m+Pgv5nsvgX6NzbmTEIFzgXwtePIlyH5PlxSJQsNmoh1UFQtUq7oJ8QhV1TmO2pHR5cGWjcGF5"
        },
        {
            "txn": "iaVjbG9zZcQg72bqZkzwHK+8VJ/d2VsSbQYzTcQ0IBVl996R6LwAtxWjZmVlzQPoomZ2zgFmL/GjZ2VurG1haW5uZXQtdjEuMKJnaMQgwGHE2Pwdvd7S12BL5FaOP20EGYesN73ktiC1qzkkit+jZ3JwxCCWRHOjsiVIKrtP6LwMJVr36TJ++RX0DVKeX2cmq+UxSaJsds4BZjPZo3NuZMQgBCjPiii5oZiEC4h1QmPp4bZV0cQzshTS7k3m/YhuzsWkdHlwZaNwYXk=",
            "signers": [
                "AQUM7CRIXGQZRBALRB2UEY7J4G3FLUOEGOZBJUXOJXTP3CDOZ3CTSEIZ4Q"
            ]
        },
        {
            "txn": "iqNhbXTOAA9CQKNmZWXNA+iiZnbOAWYv8aNnZW6sbWFpbm5ldC12MS4womdoxCDAYcTY/B293tLXYEvkVo4/bQQZh6w3veS2ILWrOSSK36NncnDEIJZEc6OyJUgqu0/ovAwlWvfpMn75FfQNUp5fZyar5TFJomx2zgFmM9mjcmN2xCDvZupmTPAcr7xUn93ZWxJtBjNNxDQgFWX33pHovAC3FaNzbmTEIFzgXwtePIlyH5PlxSJQsNmoh1UFQtUq7oJ8QhV1TmO2pHR5cGWjcGF5"
        }
    ]
]

**Comment by janmarcano** [comment]
Given your last example, the signers provided on positions `[2]` and `[4]` of the group will impede the signing as they're not empty. If your intention is to sign them afterwards with a logicsig, then `signers: []` needs to be provided on that tx.
For the rest of the transactions, no `signers` should be provided for them to be signed normally.

Here's how the tx on `[2]` and `[4]` should look like if they were meant to be the reference txs meant for later logicsig signing:
```
{ "txn": ... },
{ "txn": ... },
{
  "txn": "jKRhYW10AaZhY2xvc2XEIO9m6mZM8ByvvFSf3dlbEm0GM03ENCAVZffekei8ALcVpGFyY3bEIFzgXwtePIlyH5PlxSJQsNmoh1UFQtUq7oJ8QhV1TmO2o2ZlZc0D6KJmds4BZi/xo2dlbqxtYWlubmV0LXYxLjCiZ2jEIMBhxNj8Hb3e0tdgS+RWjj9tBBmHrDe95LYgtas5JIrfo2dycMQglkRzo7IlSCq7T+i8DCVa9+kyfvkV9A1Snl9nJqvlMUmibHbOAWYz2aNzbmTEIAQoz4oouaGYhAuIdUJj6eG2VdHEM7IU0u5N5v2Ibs7FpHR5cGWlYXhmZXKkeGFpZM4zqd1q",
  "signers": []
},
{ "txn": ... },
{
  "txn": "iaVjbG9zZcQg72bqZkzwHK+8VJ/d2VsSbQYzTcQ0IBVl996R6LwAtxWjZmVlzQPoomZ2zgFmL/GjZ2VurG1haW5uZXQtdjEuMKJnaMQgwGHE2Pwdvd7S12BL5FaOP20EGYesN73ktiC1qzkkit+jZ3JwxCCWRHOjsiVIKrtP6LwMJVr36TJ++RX0DVKeX2cmq+UxSaJsds4BZjPZo3NuZMQgBCjPiii5oZiEC4h1QmPp4bZV0cQzshTS7k3m/YhuzsWkdHlwZaNwYXk=",
  "signers": []
},
{ "txn": ... },
```
