### ISSUE TITLE
Is this library actively maintained? 

### ISSUE THREAD

**Issue by gessic-apps** [PureStake/algosigner#483]
With the recent hack of MyAlgo wallet, protocols are looking to support web wallets. It seems Algosigner may not be popular, but its audited and open sourced. The question is, is it actively maintained? Are security issues that comeup resolved by a dedicated team?

**Comment by purestaketdb** [comment]
AlgoSigner will cease being maintained and supported on March 31st, 2023. There was an active development team supporting it and it had been audited several times in the past.
