### ISSUE TITLE
Support for BetaNet

### ISSUE THREAD

**Issue by Uberi** [PureStake/algosigner#90]
First of all, really excited to see this being released so soon! It's definitely a big step up from copy/pasting `goal` commands.

Is support for BetaNet planned for the future? The extension currently seems to support MainNet and TestNet.

**Comment by purestaketdb** [comment]
Ability to add any defined network planned for Dec/Jan -

**Comment by purestaketdb** [comment]
With the latest release you may add BetaNet or any other network to AlgoSigner to work with.
