### ISSUE TITLE
Define what is wrong with txnObject when calling AlgoSigner.sign() method.

### ISSUE THREAD

**Issue by MamoonAhmad** [PureStake/algosigner#97]
Current implementation does not emit a clear error about what is wrong with txnObject. So for example if `to` address is not valid, AlgoSigner should emit an error clearly identifying that `"To Address is not valid."` . Instead it says `"Some properties are not valid."`. This is very hard to debug as user does not have a way to determine what's wrong with the object.

**Comment by purestaketdb** [comment]
Agreed, the validation is under review to improve both how the validation checks the transaction and how it responds to the developer. 

When we have the changes fully fleshed out, we will update here.

**Comment by purestaketdb** [comment]
Additional errors and messages included in https://github.com/PureStake/algosigner/releases/tag/v1.1.0
